### PR TITLE
[BB-6300] fix: inconsistency in grabbed draggable item width

### PR DESCRIPTION
**Pull request by kaustavb12**
## Description

This PR fixes inconsistencies in the width of draggable items when grabbed from a drop zone.

The width/maxWidth of a draggable item is calculated in percentage according to the width of the drop zone.

When an item is grabbed from a drop zone, the item is moved to the draggable area div, whose width is larger than the drop zone, and so calculated width percentage of the item would now be in relation to the entire draggable area.

This let to inconsistencies, if different drop zone were of different widths and/or the width of the last drop zone is smaller than the actual width of the draggable item.

**Before:**
Before

**After:**
After

## Supporting information

OpenCraft internal ticket [BB-6300](https://tasks.opencraft.com/browse/BB-6300)

## Testing instructions

1. Checkout this branch in `<devstack_parent>/src` directory in your local setup
2. Login to Studio shell, switch to `edxapp` virtual env
3. Go to `/edx/src/xblock-drag-and-drop-v2` and run `pip install -e .`
4. Go to Studio UI and create a new unit
5. Select `Problem` > `Advanced` > `Drag and Drop`, to create a v2 drag and drop xblock
6. Click `Edit` and change mode to `Assessment`
7. Click `Continue` twice
8. Scroll down to first item definition, click on `Show advanced settings` and set preferred width to `50%`
9. Click `Save`
10. Grab the item for which the width was just set. Visually note the width of the item
11.  Drop it to the top zone
12. Grab the item again from the top zone, the item width should equal to the width when first grabbed.
13. Drop the item to the bottom zone
14. Grab the item again from the bottom zone, the item width should be equal to width when first grabbed.

## Deadline

"None" if there's no rush, or provide a specific date or event (and reason) if there is one.

## Other information

Include anything else that will help reviewers and consumers understand the change.
- Does this change depend on other changes elsewhere?
- Any special concerns or limitations? For example: deprecations, migrations, security, or accessibility.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @kaustavb12! I've created [OSPR-6767](https://openedx.atlassian.net/browse/OSPR-6767) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @kaustavb12! I've created [OSPR-6768](https://openedx.atlassian.net/browse/OSPR-6768) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@kaustavb12 Please let me know once this is ready for our review.

**Comment by kaustavb12** [comment]
@natabene  For sure. I'll ping you here once ready.

@natabene @Agrendalath 
The test case failure seems to be unrelated to the changes here.
I have added an empty commit to trigger it again, but it needs approval from a maintainer to run. Could you please trigger it again.

**Review by Agrendalath — APPROVED** [review]
:+1:

* [x]  I tested this: verified the described behavior
* [x]  I read through the code
* [x]  I checked for accessibility issues: n/a
* [x]  Includes documentation
* [x] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository: n/a

**Comment by Agrendalath** [comment]
@natabene, please let me know if you'd like to take a look at this before I merge it.

**Comment by natabene** [comment]
@Agrendalath Please feel free to merge.

**Comment by openedx-webhooks** [comment]
@kaustavb12 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/xblock-drag-and-drop-v2&entry.867055334=https://github.com/openedx/xblock-drag-and-drop-v2/pull/285&entry.1484655318=https://github.com/kaustavb12&entry.752974735=2022-06-08+07:43&entry.1917517419=2022-06-15+16:23&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
