### PR TITLE
Build: add test path as an optional parameter to test.unit command

### PR DESCRIPTION
**Pull request by abodacs**
This:

- add an optional test path like ```tests.integration.test_interaction_assessment``` to  Makefile command ```test.unit```

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @abodacs!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @abodacs!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by Agrendalath** [comment]
@abodacs, please document this in the README.

**Comment by Agrendalath** [comment]
@natabene, would you like to take a look at this before we merge it? This is a small change, but I thought I'll ask you to be sure.

**Comment by natabene** [comment]
@Agrendalath Thanks for checking, I don't, but @jmbowman might.

**Review by Agrendalath — APPROVED** [review]
:+1:

* [x] I tested this: checked that it's possible to run particular test classes and tests
* [x] I read through the code
* [x] I checked for accessibility issues: n/a
* [x] Includes documentation
* [x] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository: n/a

**Comment by openedx-webhooks** [comment]
@abodacs 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/xblock-drag-and-drop-v2&entry.867055334=https://github.com/openedx/xblock-drag-and-drop-v2/pull/296&entry.1484655318=https://github.com/abodacs&entry.752974735=2022-09-30+15:31&entry.1917517419=2022-10-13+11:29&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
