### PR TITLE
[BB-6465] Change help text under submit button

### PR DESCRIPTION
**Pull request by tecoholic**
When multiple attempts are enabled, the help text reads
"You have used x of y attempts.". This commit changes the help text
to "You have used x of y submissions"

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @tecoholic!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @tecoholic!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by tecoholic** [comment]
@Agrendalath I used the `make extract_translations`, `compile_translations` and `validate_translations` to update the text. However, it updated only a couple of translation files, and a lot of the languages still have the old text in them. I have put this PR in draft until I figure out how to update them properly. Kindly let me know if there is something missing in the README that could be of help here.

**Comment by tecoholic** [comment]
@Agrendalath I have pulled all the translations using `make pull_translations`, replaced the help text in all the translation files and translated js files using 
```
find . -name *.po -o -name *.js | xargs sed -i 's/You have used {used} of {total} attempts./You have used {used} of {total} submissions/g'
```
and then ran `make compile_translations` (which I think, I should have run earlier after pull).

**Comment by Agrendalath** [comment]
@tecoholic, the described styling comes from the custom theme, so let's close this. I've reverted the pushed Transifex changes.

**Comment by openedx-webhooks** [comment]
@tecoholic Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/xblock-drag-and-drop-v2&entry.867055334=https://github.com/openedx/xblock-drag-and-drop-v2/pull/288&entry.1484655318=https://github.com/tecoholic&entry.752974735=2022-07-15+09:21&entry.1917517419=2022-07-20+17:58&entry.2133058324=No) so we can improve your experience in the future.

**Comment by openedx-webhooks** [comment]
@tecoholic Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/xblock-drag-and-drop-v2&entry.867055334=https://github.com/openedx/xblock-drag-and-drop-v2/pull/288&entry.1484655318=https://github.com/tecoholic&entry.752974735=2022-07-15+09:21&entry.1917517419=2022-07-20+17:58&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
