### PR TITLE
build: update CI workflows and add pip-tools

### PR DESCRIPTION
**Pull request by Agrendalath**
This:
1. Adds missing GitHub workflows.
2. Adds a template for PRs.
3. Optimizes existing GitHub workflows.
4. Updates the translations.
5. Modernizes `setup.py` and moves the package version to `__init__.py`.
6. Upgrades Django to 3.2 (from 1.11) and fixes non-deterministic tests that started failing after the upgrade.
7. Upgrades `xblock-sdk` to the latest version and removes the submodule.
8. Adds `pip-tools` to logically organize dependencies and allow scheduled requirements updates.
9. Adds `tox` to simplify the testing setup.

Notes: I wanted to switch integration tests to `pytest`, but two tests get the `AssertionError: 'Unable to connect' != 'XBlock scenarios'` exception from the workbench when running the whole test suite. If I run them separately, they pass without any trouble. After some debugging, I decided to leave this as is.

## Review instructions
It will be easier to review this commit by commit.

## Testing instructions
1. Run the testing suite as described in the updated `README`.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Agrendalath!

As a core committer in this repo, you can merge this once the pull request is approved per the [core committer reviewer requirements](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1529675973/Open+edX+Core+Committers#Reviews-and-Ownership) and according to the agreement with your edX Champion.

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Agrendalath!

As a core committer in this repo, you can merge this once the pull request is approved per the [core committer reviewer requirements](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1529675973/Open+edX+Core+Committers#Reviews-and-Ownership) and according to the agreement with your edX Champion.

**Review by 0x29a — APPROVED** [review]
:+1:

- [x] I tested this by running `make tests` locally.
- [x] I read through the changes.
- [x] Includes documentation.

**Comment by openedx-webhooks** [comment]
@Agrendalath 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/xblock-drag-and-drop-v2&entry.867055334=https://github.com/openedx/xblock-drag-and-drop-v2/pull/310&entry.1484655318=https://github.com/Agrendalath&entry.752974735=2023-02-09+17:41&entry.1917517419=2023-03-02+17:34&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by openedx-webhooks** [comment]
@Agrendalath 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/xblock-drag-and-drop-v2&entry.867055334=https://github.com/openedx/xblock-drag-and-drop-v2/pull/310&entry.1484655318=https://github.com/Agrendalath&entry.752974735=2023-02-09+17:41&entry.1917517419=2023-03-02+17:34&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
